const diagnosis=[
    { label: "Allergy Conjuctivitis", value: "Allergy Conjustivitis" },
    { label: "Conjuctivitis", value: "Conjuctivitis" },
    { label: "Viral Conjuctivitis", value: "Viral Conjuctivitis" },
    {
      label: "Vernal KeratoConjuctivitis (Spring catarrh)",
      value: "Vernal KeratoConjuctivitis (Spring catarrh)",
    },
    { label: "Refractive Errors", value: "Refractive Errors" },
    { label: "Myopia", value: "Myopia" },
    { label: "High-Myopia", value: "High-Myopia" },
    { label: "Hypermatropia", value: "Hypermatropia" },
    { label: "Astigmatism", value: "Astigmatism" },
    { label: "Presbyopia", value: "Presbyopia" },
    { label: "No Acceptance of Glasses", value: "No Acceptance of Glasses" },
    { label: "Dry Eyes", value: "Dry Eyes" },
    { label: "Computer Vision Syndrome", value: "Computer Vision Syndrome" },
    { label: "Blepharitis", value: "Blepharitis" },
    { label: "trachoma", value: "trachoma" },
    {
      label: "Age related Macular Degeneration",
      value: "Age related Macular Degeneration",
    },
    { label: "Cataract", value: "Cataract" },
    { label: "Diabetic Retinopathy", value: "Diabetic Retinopathy" },
    { label: "Glaucoma", value: "Glaucoma" },
    { label: "Amblyopia", value: "Amblyopia" },
    { label: "Keratitis", value: "Keratitis" },
    { label: "Ocular herpes", value: "Ocular herpes" },
    { label: "herpes zoster", value: "herpes zoster" },
    { label: "Corneal dystrophies", value: "Corneal dystrophies" },
    { label: "Keratoconus", value: "Keratoconus" },
    { label: "Corneal Ulcer", value: "Corneal Ulcer" },
    { label: "Bullous keratopathy", value: "Bullous keratopathy" },
    { label: "Cogan Syndrome", value: "Cogan Syndrome" },
    { label: "Interstitial keratitis", value: "Interstitial keratitis" },
    { label: "KeratoConjuctivitis sicca", value: "KeratoConjuctivitis sicca" },
    { label: "Keratomalacia", value: "Keratomalacia" },
    {
      label: "Peripheral ulcerative keratitis",
      value: "Peripheral ulcerative keratitis",
    },
    {
      label: "Phlyctenular keratoconjuctivitis",
      value: "Phlyctenular keratoconjuctivitis",
    },
    {
      label: "Superficial punctate keratitis",
      value: "Superficial punctate keratitis",
    },
    { label: "CRVO", value: "CRVO" },
    { label: "BRVO", value: "BRVO" },
    { label: "RD", value: "RD" },
    { label: "CSME", value: "CSME" },
    { label: "CSMD", value: "CSMD" },
  ]

  export default diagnosis;