const treatmentt=[
    { label: "OFLUS", value: "OFLUS" },
    { label: "GATFLOS", value: "GATFLOS" },
    { label: "MOFLUS-T", value: "MOFLUS-T" },
    { label: "MOFLUS", value: "MOFLUS" },
    { label: "TINIC", value: "TINIC" },
    { label: "ANANAC", value: "ANANAC" },
    { label: "KETEXO", value: "KETEXO" },
    { label: "MOFLUS-KT", value: "MOFLUS-KT" },
    { label: "OKULAC", value: "OKULAC" },
    { label: "OKULAC-D", value: "OKULAC-D" },
    { label: "OKULAC-AH", value: "OKULAC-AH" },
    { label: "ZYFLUR", value: "ZYFLUR" },
    { label: "MOFLUS-BR", value: "MOFLUS-BR" },
    { label: "OKULAC-LS", value: "OKULAC-LS" },
    { label: "GATFLOS-F", value: "GATFLOS-F" },
    { label: "ACT-ONE250", value: "ACT-ONE250" },
    { label: "TIMOLUS-BT", value: "TIMOLUS-BT" },
    { label: "GATFLOS-B", value: "GATFLOS-B" },
    { label: "HOLIF", value: "HOLIF" },
    { label: "HOLIF-T", value: "HOLIF-T" },
    { label: "MOFLUS-B", value: "MOFLUS-B" },
    { label: "OFLUS-D", value: "OFLUS-D" },
    { label: "P-REX-B", value: "P-REX-B" },
    { label: "MOFLUS-LT", value: "MOFLUS-LT" },
    { label: "LAPT", value: "LAPT" },
    { label: "PREXO", value: "PREXO" },
    { label: "MOFLUS-P", value: "MOFLUS-P" },
    { label: "MOFLUS-D", value: "MOFLUS-D" },
    { label: "HYON-C", value: "HYON-C" },
    { label: "NATOK", value: "NATOK" },
    { label: "CUCOLUS", value: "CUCOLUS" },
    { label: "PATINE", value: "PATINE" },
    { label: "PUPILOWIDE", value: "PUPILOWIDE" },
    { label: "CATLUS", value: "CATLUS" },
    { label: "STAY SOFT", value: "STAY SOFT" },
    { label: "CARMOS", value: "CARMOS" },
    { label: "CARMOS GEL", value: "CARMOS GEL" },
    { label: "CARMOS-LS", value: "CARMOS-LS" },
    { label: "CARMOS-PLUS", value: "CARMOS-PLUS" },
    { label: "H-MOS", value: "H-MOS" },
    { label: "OSS", value: "OSS" },
    { label: "LYOK-5000", value: "LYOK-5000" },
    { label: "LYOK-VIT", value: "LYOK-VIT" },
    { label: "VITLUS", value: "VITLUS" },
    { label: "LYOKPLUS", value: "LYOKPLUS" },
    { label: "SIGHTSOFT", value: "SIGHTSOFT" },
    { label: "ME9X-OD", value: "ME9X-OD" },
    { label: "AIMS", value: "AIMS" },
    { label: "AIMS-OD", value: "AIMS-OD" },
    { label: "AIMS-KT", value: "AIMS-KT" },
    { label: "HPNC", value: "HPNC" },
    { label: "HPNC PLUS", value: "HPNC PLUS" },
    { label: "ROMAG", value: "ROMAG" },
    { label: "ACLON-P", value: "ACLON-P" },
    { label: "ACLON-SP", value: "ACLON-SP" },
    { label: "ADD-5", value: "ADD-5" },
    { label: "RIOS", value: "RIOS" },
    { label: "RIOS PLUS", value: "RIOS PLUS" },
    { label: "DEFLUS-6", value: "DEFLUS-6" },
    { label: "FEXOLUS-M", value: "FEXOLUS-M" },
    { label: "GABLUS-M", value: "GABLUS-M" },
    { label: "CFDM-200", value: "CFDM-200" },
    { label: "ROXUS-150", value: "ROXUS-150" },
    { label: "DRYCURE", value: "DRYCURE" },
    { label: "DRYCURE GEL", value: "DRYCURE GEL" },
    { label: "DRYCURE ULTRA", value: "DRYCURE ULTRA" },
    { label: "MCN", value: "MCN" },
    { label: "MCN KT", value: "MCN KT" },
    { label: "NEFACURE", value: "NEFACURE" },
    { label: "KETCURE-CP", value: "KETCURE-CP" },
    { label: "FLUROCURE-T", value: "FLUROCURE-T" },
    { label: "PATACURE", value: "PATACURE" },
    { label: "CATACURE", value: "CATACURE" },
    { label: "TIMCURE", value: "TIMCURE" },
    { label: "LYCURE", value: "LYCURE" },
    { label: "FANDUS", value: "FANDUS" },
    { label: "CATASOL", value: "CATASOL" },
    { label: "HUMOX", value: "HUMOX" },
    { label: "OPTOBS", value: "OPTOBS" },
    { label: "HUCIN-P", value: "HUCIN-P" },
    { label: "TEARIN", value: "TEARIN" },
    { label: "HUNAC", value: "HUNAC" },
    { label: "HUCROM", value: "HUCROM" },
    { label: "ALTEARS", value: "ALTEARS" },
    { label: "OCLAC", value: "OCLAC" },
    { label: "DR-SONI-P", value: "DR-SONI-P" },
    { label: "FLUTON", value: "FLUTON" },
    { label: "HUMOX-K", value: "HUMOX-K" },
    { label: "VIBS", value: "VIBS" },
    { label: "HUDIN", value: "HUDIN" },
    { label: "AKXN", value: "AKXN" },
    { label: "ATPINE", value: "ATPINE" },
    { label: "B-FAX", value: "B-FAX" },
    { label: "B-MOX", value: "B-MOX" },
    { label: "CLODIL", value: "CLODIL" },
    { label: "DD", value: "DD" },
    { label: "DEPOL", value: "DEPOL" },
    { label: "FLUROM", value: "FLUROM" },
    { label: "FLUROM-T", value: "FLUROM-T" },
    { label: "GATSAR", value: "GATSAR" },
    { label: "GSP", value: "GSP" },
    { label: "GLUMA", value: "GLUMA" },
    { label: "HYLUR", value: "HYLUR" },
    { label: "I-BRO", value: "I-BRO" },
    { label: "IFAX", value: "IFAX" },
    { label: "IFAX-D", value: "IFAX-D" },
    { label: "KEMAC", value: "KEMAC" },
    { label: "KEMAC-D", value: "KEMAC-D" },
    { label: "KEMAC-M", value: "KEMAC-M" },
    { label: "LENSACT", value: "LENSACT" },
    { label: "LOTEMIL", value: "LOTEMIL" },
    { label: "MILINEUM", value: "MILINEUM" },
    { label: "MYGIC", value: "MYGIC" },
    { label: "NPF", value: "NPF" },
    { label: "NTM", value: "NTM" },
    { label: "OPEDE", value: "OPEDE" },
    { label: "PREDSAR", value: "PREDSAR" },
    { label: "PROCAINE", value: "PROCAINE" },
    { label: "POVICARE", value: "POVICARE" },
    { label: "PG-AQUA", value: "PG-AQUA" },
    { label: "REAL TEARS", value: "REAL TEARS" },
    { label: "SOCL", value: "SOCL" },
    { label: "TEARFILM", value: "TEARFILM" },
    { label: "TEARFILM GEL", value: "TEARFILM GEL" },
    { label: "TORBIS", value: "TORBIS" },
    { label: "ZED+B-FAX", value: "ZED+B-FAX" },
    { label: "MILINIUM", value: "MILINIUM" },
    { label: "REAL GEL", value: "REAL GEL" },
    { label: "ATEASE-10", value: "ATEASE-10" },
    { label: "ASDM", value: "ASDM" },
    { label: "OPT", value: "OPT" },
    { label: "SOURCE", value: "SOURCE" },
    { label: "SEE ON", value: "SEE ON" },
    { label: "SEE MEGA", value: "SEE MEGA" },
    { label: "PROTIMES", value: "PROTIMES" },
    { label: "AKSHCARE", value: "AKSHCARE" },
    { label: "ALOTE", value: "ALOTE" },
    { label: "AYURFAX", value: "AYURFAX" },
  ]

  export default treatmentt;